
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'httptrigger'

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    repository: $(imageName)
    tags: latest
    command: buildAndPush
    Dockerfile: $(System.DefaultWorkingDirectory)/Dockerfile
    containerRegistry: jackcontainerreg

- task: Kubernetes@1
  displayName: Delete Kubernetes objects
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: MCAPS-Hybrid-REQ-42760-2022-JackXue (6879fc1e-5aa4-49d6-8bde-b9577bb6d594)
    azureResourceGroup: zediproin
    kubernetesCluster: zediproinaks
    command: delete
    arguments: -f $(System.DefaultWorkingDirectory)/func-kerctl-aks.yml

- task: Kubernetes@1
  displayName: Deploy to Kubernetes cluster
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: MCAPS-Hybrid-REQ-42760-2022-JackXue (6879fc1e-5aa4-49d6-8bde-b9577bb6d594)
    azureResourceGroup: zediproin
    kubernetesCluster: zediproinaks
    command: apply
    arguments: -f $(System.DefaultWorkingDirectory)/func-kerctl-aks.yml
